spring.application.name=superhotel

#Database
spring.datasource.url = jdbc:oracle:thin:@host.docker.internal:1521:oracle
spring.datasource.username = DEV_SUPERHOTEL
spring.datasource.password = dev
spring.datasource.driver-class-name = oracle.jdbc.OracleDriver

#Jpa-Hibernate
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB